export const GET_REPORT_START = "GET_REPORT_START";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_FAILER = "GET_REPORT_FAILER";

export const GET_REPORT_BY_USER_START = "GET_REPORT_BY_USER_START";
export const GET_REPORT_BY_USER_SUCCESS = "GET_REPORT_BY_USER_SUCCESS";
export const GET_REPORT_BY_USER_FAILER = "GET_REPORT_BY_USER_FAILER";