export const GET_TEACHER_START = "GET_TEACHER_START";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAILER = "GET_TEACHER_FAILER";

export const GET_TEACHER_ALL_START = "GET_TEACHER_ALL_START";
export const GET_TEACHER_ALL_SUCCESS = "GET_TEACHER_ALL_SUCCESS";
export const GET_TEACHER_ALL_FAILER = "GET_TEACHER_ALL_FAILER";


export const ADD_TEACHER_START = "ADD_TEACHER_START";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAILER = "ADD_TEACHER_FAILER";

export const EDIT_TEACHER_START = "EDIT_TEACHER_START";
export const EDIT_TEACHER_SUCCESS = "EDIT_TEACHER_SUCCESS";
export const EDIT_TEACHER_FAILER = "EDIT_TEACHER_FAILER";

export const DELETE_TEACHER_START = "DELETE_TEACHER_START";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILER = "DELETE_TEACHER_FAILER";