export const GET_TEACHER_START = "GET_TEACHER_START";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAILER = "GET_TEACHER_FAILER";

export const GET_TEACHER_ALL_START = "GET_TEACHER_ALL_START";
export const GET_TEACHER_ALL_SUCCESS = "GET_TEACHER_ALL_SUCCESS";
export const GET_TEACHER_ALL_FAILER = "GET_TEACHER_ALL_FAILER";