export const SET_MODE_START = "SET_MODE_START";
export const SET_MODE_SUCCESS = "SET_MODE_SUCCESS";
export const SET_MODE_FAILER = "SET_MODE_FAILER";

export const SET_COLOR_START = "SET_COLOR_START";
export const SET_COLOR_SUCCESS = "SET_COLOR_SUCCESS";
export const SET_COLOR_FAILER = "SET_COLOR_FAILER";


export const GET_THEME_START = "GET_THEME_START";
export const GET_THEME_SUCCESS = "GET_THEME_SUCCESS";
export const GET_THEME_FAILER = "GET_THEME_FAILER";